/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './src/renderer/index.html',
    './src/renderer/src/**/*.{js,ts,jsx,tsx}',
    './src/pwa/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45464d',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#76777d',
        'outline-variant': '#c6c6cd',
        'surface-tint': '#565e74',
        'primary': '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        'inverse-primary': '#bec6e0',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'secondary': '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#82f5c1',
        'on-secondary-container': '#00714e',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        'tertiary': '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#2f1500',
        'on-tertiary-container': '#c76c00',
        'tertiary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#ffb77d',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#6e3900',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'spacing-2xs': '0.125rem',
        'spacing-xs': '0.25rem',
        'spacing-sm': '0.5rem',
        'spacing-md': '0.75rem',
        'spacing-base': '1rem',
        'spacing-lg': '1.25rem',
        'spacing-xl': '1.5rem',
        'spacing-2xl': '2rem',
        'gutter-desktop': '1rem',
        'table-cell-py': '0.375rem',
        'table-cell-px': '0.75rem',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'caption': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'currency-md': ['JetBrains Mono', 'monospace'],
        'currency-lg': ['JetBrains Mono', 'monospace'],
        'currency-xl': ['JetBrains Mono', 'monospace'],
        'tabular-label': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'caption': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-lg': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['15px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'tabular-label': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'currency-md': ['13px', { lineHeight: '16px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'currency-lg': ['18px', { lineHeight: '24px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'currency-xl': ['26px', { lineHeight: '32px', letterSpacing: '-0.03em', fontWeight: '700' }],
      }
    },
  },
  plugins: [],
};
